/* Generated by Yosys 0.38+129 (git sha1 e9cd6ca9e, g++ 13.2.0-4ubuntu3 -fPIC -Os) */

(* top =  1  *)
(* src = "./blinky.v:1.1-13.10" *)
module top(rst, leds, clk);
  (* ROUTING = {0{1'b0}} *)
  wire _00_;
  (* ROUTING = {0{1'b0}} *)
  wire _01_;
  (* ROUTING = "X2/Y4/SLICE0_LUT1;X2/Y4/SLICE2_OUT0_to_SLICE0_IN1_FEEDBACK;1;X3/Y2/CHANNEL14;X3/Y3/WN_CHANNEL14;1;X2/Y2/EAST_IN2;X3/Y2/QCB_TO_CLB_EAST_IN2_CHANNEL14;1;X2/Y2/SLICE1_LUT2;X2/Y2/SLICE1_EAST_IN_LUT2;1;X2/Y2/SLICE0_LUT3;X2/Y2/SLICE0_SOUTH_IN_LUT3;1;X2/Y4/SLICE2_F;;1;X2/Y4/NORTH_OUT0;X2/Y4/SLICE2_NORTH_OUT_F;1;X2/Y3/CHANNEL14;X2/Y3/CLB_TO_QCB_NORTH_OUT0_CHANNEL14;1;X2/Y2/SOUTH_IN3;X2/Y3/QCB_TO_CLB_SOUTH_IN3_CHANNEL14;1;X2/Y2/SLICE3_LUT3;X2/Y2/SLICE3_SOUTH_IN_LUT3;1" *)
  wire _02_;
  (* ROUTING = "X2/Y2/SLICE3_F;;1;X2/Y2/SLICE2_LUT1;X2/Y2/SLICE3_OUT0_to_SLICE2_IN1_FEEDBACK;1" *)
  wire _03_;
  (* ROUTING = "X2/Y2/EAST_IN5;X3/Y2/QCB_TO_CLB_EAST_IN5_CHANNEL13;1;X2/Y2/SLICE_CLK;X2/Y2/SLICE_CLK_EAST_IN;1;X4/Y3/CHANNEL13;X3/Y3/NE_CHANNEL13;1;X4/Y4/NORTH_IN5;X4/Y3/QCB_TO_CLB_NORTH_IN5_CHANNEL13;1;X4/Y4/SLICE_CLK;X4/Y4/SLICE_CLK_NORTH_IN;1;X4/Y2/NORTH_IN5;X4/Y1/QCB_TO_CLB_NORTH_IN5_CHANNEL13;1;X4/Y2/SLICE_CLK;X4/Y2/SLICE_CLK_NORTH_IN;1;X4/Y0/IO0_O;;1;X4/Y1/CHANNEL13;X4/Y1/IOB_TO_QCB_SOUTH_OUT0_CHANNEL13;1;X3/Y2/CHANNEL13;X3/Y1/ES_CHANNEL13;1;X3/Y4/CHANNEL13;X3/Y3/NS_CHANNEL13;1;X2/Y4/EAST_IN5;X3/Y4/QCB_TO_CLB_EAST_IN5_CHANNEL13;1;X2/Y4/SLICE_CLK;X2/Y4/SLICE_CLK_EAST_IN;1" *)
  wire _04_;
  (* ROUTING = "X4/Y3/CHANNEL14;X3/Y3/SE_CHANNEL14;1;X4/Y2/SOUTH_IN5;X4/Y3/QCB_TO_CLB_SOUTH_IN5_CHANNEL14;1;X4/Y2/SLICE_RST_N;X4/Y2/SLICE_RST_N_SOUTH_IN;1;X2/Y4/SOUTH_IN5;X2/Y5/QCB_TO_CLB_SOUTH_IN5_CHANNEL14;1;X2/Y4/SLICE_RST_N;X2/Y4/SLICE_RST_N_SOUTH_IN;1;X3/Y4/CHANNEL14;X3/Y5/WN_CHANNEL14;1;X4/Y4/WEST_IN5;X3/Y4/QCB_TO_CLB_WEST_IN5_CHANNEL14;1;X4/Y4/SLICE_RST_N;X4/Y4/SLICE_RST_N_WEST_IN;1;X2/Y6/IO1_O;;1;X2/Y5/CHANNEL14;X2/Y5/IOB_TO_QCB_NORTH_OUT1_CHANNEL14;1;X1/Y4/CHANNEL14;X1/Y5/DUMMY1_CHANNEL14;1;X1/Y2/CHANNEL14;X1/Y3/SN_CHANNEL14;1;X2/Y2/WEST_IN5;X1/Y2/QCB_TO_CLB_WEST_IN5_CHANNEL14;1;X2/Y2/SLICE_RST_N;X2/Y2/SLICE_RST_N_WEST_IN;1" *)
  wire _05_;
  (* ROUTING = "X4/Y2/SLICE0_F;;1;X4/Y2/SLICE0_D;X4/Y2/SLICE0_OUT0_to_SLICE0_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _06_;
  (* ROUTING = "X4/Y4/SLICE0_F;;1;X4/Y4/SLICE0_D;X4/Y4/SLICE0_OUT0_to_SLICE0_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _07_;
  (* ROUTING = "X2/Y4/SLICE3_F;;1;X2/Y4/SLICE3_D;X2/Y4/SLICE3_OUT0_to_SLICE3_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _08_;
  (* ROUTING = "X2/Y4/SLICE1_F;;1;X2/Y4/SLICE1_D;X2/Y4/SLICE1_OUT0_to_SLICE1_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _09_;
  (* ROUTING = "X2/Y4/SLICE0_F;;1;X2/Y4/SLICE0_D;X2/Y4/SLICE0_OUT0_to_SLICE0_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _10_;
  (* ROUTING = "X2/Y2/SLICE1_F;;1;X2/Y2/SLICE1_D;X2/Y2/SLICE1_OUT0_to_SLICE1_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _11_;
  (* ROUTING = "X2/Y2/SLICE0_F;;1;X2/Y2/SLICE0_D;X2/Y2/SLICE0_OUT0_to_SLICE0_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _12_;
  (* ROUTING = "X2/Y2/SLICE2_F;;1;X2/Y2/SLICE2_D;X2/Y2/SLICE2_OUT0_to_SLICE2_IN4_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:8.10-8.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _13_;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.32-1.35" *)
  input clk;
  wire clk;
  (* ROUTING = "X4/Y2/SLICE0_LUT0;X4/Y2/SLICE0_OUT1_to_SLICE0_IN0_FEEDBACK;1;X4/Y2/SOUTH_OUT1;X4/Y2/SLICE0_SOUTH_OUT_Q;1;X4/Y3/CHANNEL15;X4/Y3/CLB_TO_QCB_SOUTH_OUT1_CHANNEL15;1;X4/Y4/NORTH_IN1;X4/Y3/QCB_TO_CLB_NORTH_IN1_CHANNEL15;1;X4/Y4/SLICE0_LUT1;X4/Y4/SLICE0_NORTH_IN_LUT1;1;X3/Y2/CHANNEL12;X3/Y2/CLB_TO_QCB_WEST_OUT1_CHANNEL12;1;X2/Y3/CHANNEL12;X3/Y3/NW_CHANNEL12;1;X2/Y4/NORTH_IN2;X2/Y3/QCB_TO_CLB_NORTH_IN2_CHANNEL12;1;X2/Y4/SLICE3_LUT2;X2/Y4/SLICE3_NORTH_IN_LUT2;1;X2/Y4/SLICE1_LUT3;X2/Y4/SLICE1_NORTH_IN_LUT3;1;X4/Y2/SLICE0_Q;;1;X4/Y2/WEST_OUT1;X4/Y2/SLICE0_WEST_OUT_Q;1;X3/Y2/CHANNEL1;X3/Y2/CLB_TO_QCB_WEST_OUT1_CHANNEL1;1;X2/Y3/CHANNEL1;X3/Y3/NW_CHANNEL1;1;X2/Y4/NORTH_IN3;X2/Y3/QCB_TO_CLB_NORTH_IN3_CHANNEL1;1;X2/Y4/SLICE2_LUT3;X2/Y4/SLICE2_NORTH_IN_LUT3;1" *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[0] ;
  (* ROUTING = "X4/Y4/SLICE0_LUT0;X4/Y4/SLICE0_OUT1_to_SLICE0_IN0_FEEDBACK;1;X2/Y4/SLICE1_LUT2;X2/Y4/SLICE1_EAST_IN_LUT2;1;X3/Y4/CHANNEL15;X3/Y4/CLB_TO_QCB_WEST_OUT1_CHANNEL15;1;X2/Y4/EAST_IN1;X3/Y4/QCB_TO_CLB_EAST_IN1_CHANNEL15;1;X2/Y4/SLICE3_LUT1;X2/Y4/SLICE3_EAST_IN_LUT1;1;X4/Y4/SLICE0_Q;;1;X4/Y4/WEST_OUT1;X4/Y4/SLICE0_WEST_OUT_Q;1;X3/Y4/CHANNEL6;X3/Y4/CLB_TO_QCB_WEST_OUT1_CHANNEL6;1;X2/Y4/EAST_IN2;X3/Y4/QCB_TO_CLB_EAST_IN2_CHANNEL6;1;X2/Y4/SLICE2_LUT2;X2/Y4/SLICE2_EAST_IN_LUT2;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[1] ;
  (* ROUTING = "X2/Y4/SLICE1_LUT1;X2/Y4/SLICE3_OUT1_to_SLICE1_IN1_FEEDBACK;1;X2/Y4/SLICE3_LUT0;X2/Y4/SLICE3_OUT1_to_SLICE3_IN0_FEEDBACK;1;X2/Y4/SLICE3_Q;;1;X2/Y4/SLICE2_LUT1;X2/Y4/SLICE3_OUT1_to_SLICE2_IN1_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[2] ;
  (* ROUTING = "X2/Y4/SLICE1_LUT0;X2/Y4/SLICE1_OUT1_to_SLICE1_IN0_FEEDBACK;1;X2/Y4/SLICE1_Q;;1;X2/Y4/SLICE2_LUT0;X2/Y4/SLICE1_OUT1_to_SLICE2_IN0_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[3] ;
  (* ROUTING = "X0/Y4/IO0_I;X1/Y4/QCB_TO_IOB_EAST_IN0_CHANNEL13;1;X2/Y4/WEST_OUT1;X2/Y4/SLICE0_WEST_OUT_Q;1;X1/Y4/CHANNEL13;X1/Y4/CLB_TO_QCB_WEST_OUT1_CHANNEL13;1;X0/Y4/IO1_I;X1/Y4/QCB_TO_IOB_EAST_IN2_CHANNEL13;1;X2/Y4/SLICE0_LUT0;X2/Y4/SLICE0_OUT1_to_SLICE0_IN0_FEEDBACK;1;X2/Y3/CHANNEL2;X2/Y3/CLB_TO_QCB_NORTH_OUT1_CHANNEL2;1;X2/Y2/SOUTH_IN1;X2/Y3/QCB_TO_CLB_SOUTH_IN1_CHANNEL2;1;X2/Y2/SLICE1_LUT1;X2/Y2/SLICE1_SOUTH_IN_LUT1;1;X2/Y2/SLICE0_LUT2;X2/Y2/SLICE0_SOUTH_IN_LUT2;1;X2/Y4/SLICE0_Q;;1;X2/Y4/NORTH_OUT1;X2/Y4/SLICE0_NORTH_OUT_Q;1;X2/Y3/CHANNEL15;X2/Y3/CLB_TO_QCB_NORTH_OUT1_CHANNEL15;1;X2/Y2/SOUTH_IN2;X2/Y3/QCB_TO_CLB_SOUTH_IN2_CHANNEL15;1;X2/Y2/SLICE3_LUT2;X2/Y2/SLICE3_SOUTH_IN_LUT2;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[4] ;
  (* ROUTING = "X6/Y2/IO1_I;X5/Y2/QCB_TO_IOB_WEST_IN2_CHANNEL2;1;X2/Y2/EAST_OUT1;X2/Y2/SLICE1_EAST_OUT_Q;1;X3/Y2/CHANNEL2;X3/Y2/CLB_TO_QCB_EAST_OUT1_CHANNEL2;1;X4/Y1/CHANNEL2;X3/Y1/SE_CHANNEL2;1;X5/Y2/CHANNEL2;X5/Y1/DUMMY1_CHANNEL2;1;X6/Y2/IO0_I;X5/Y2/QCB_TO_IOB_WEST_IN0_CHANNEL2;1;X2/Y2/SLICE0_LUT1;X2/Y2/SLICE1_OUT1_to_SLICE0_IN1_FEEDBACK;1;X2/Y2/SLICE1_LUT0;X2/Y2/SLICE1_OUT1_to_SLICE1_IN0_FEEDBACK;1;X2/Y2/SLICE1_Q;;1;X2/Y2/SLICE3_LUT1;X2/Y2/SLICE1_OUT1_to_SLICE3_IN1_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[5] ;
  (* ROUTING = "X0/Y2/IO1_I;X1/Y2/QCB_TO_IOB_EAST_IN2_CHANNEL1;1;X2/Y2/WEST_OUT1;X2/Y2/SLICE0_WEST_OUT_Q;1;X1/Y2/CHANNEL1;X1/Y2/CLB_TO_QCB_WEST_OUT1_CHANNEL1;1;X0/Y2/IO0_I;X1/Y2/QCB_TO_IOB_EAST_IN0_CHANNEL1;1;X2/Y2/SLICE0_LUT0;X2/Y2/SLICE0_OUT1_to_SLICE0_IN0_FEEDBACK;1;X2/Y2/SLICE0_Q;;1;X2/Y2/SLICE3_LUT0;X2/Y2/SLICE0_OUT1_to_SLICE3_IN0_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[6] ;
  (* ROUTING = "X2/Y0/IO1_I;X2/Y1/QCB_TO_IOB_SOUTH_IN2_CHANNEL6;1;X2/Y2/NORTH_OUT1;X2/Y2/SLICE2_NORTH_OUT_Q;1;X2/Y1/CHANNEL6;X2/Y1/CLB_TO_QCB_NORTH_OUT1_CHANNEL6;1;X2/Y0/IO0_I;X2/Y1/QCB_TO_IOB_SOUTH_IN0_CHANNEL6;1;X2/Y2/SLICE2_Q;;1;X2/Y2/SLICE2_LUT0;X2/Y2/SLICE2_OUT1_to_SLICE2_IN0_FEEDBACK;1" *)
  (* force_downto = 32'd1 *)
  (* src = "./blinky.v:3.11-3.14" *)
  wire \ctr[7] ;
  output [7:0] leds;
  wire [7:0] leds;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[0] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[1] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[2] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[3] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[4] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[5] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[6] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.54-1.58" *)
  wire \leds[7] ;
  (* ROUTING = {0{1'b0}} *)
  (* src = "./blinky.v:1.21-1.24" *)
  input rst;
  wire rst;
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y2/SLICE1_LUT" *)
  LUT #(
    .INIT(16'h0000),
    .K(32'd0)
  ) _14_ (
    .F(_00_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y2/SLICE2_LUT" *)
  LUT #(
    .INIT(16'hffff),
    .K(32'd0)
  ) _15_ (
    .F(_01_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE2_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'd4)
  ) _16_ (
    .F(_02_),
    .I({ \ctr[0] , \ctr[1] , \ctr[2] , \ctr[3]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE3_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'd4)
  ) _17_ (
    .F(_03_),
    .I({ _02_, \ctr[4] , \ctr[5] , \ctr[6]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y4/SLICE0_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(4'h6),
    .K(32'd2)
  ) _18_ (
    .F(_07_),
    .I({ \ctr[0] , \ctr[1]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE3_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(8'h6a),
    .K(32'd3)
  ) _19_ (
    .F(_08_),
    .I({ \ctr[0] , \ctr[1] , \ctr[2]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE1_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(16'h6aaa),
    .K(32'd4)
  ) _20_ (
    .F(_09_),
    .I({ \ctr[0] , \ctr[1] , \ctr[2] , \ctr[3]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE0_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(4'h6),
    .K(32'd2)
  ) _21_ (
    .F(_10_),
    .I({ _02_, \ctr[4]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE1_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(8'h6a),
    .K(32'd3)
  ) _22_ (
    .F(_11_),
    .I({ _02_, \ctr[4] , \ctr[5]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE0_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(16'h6aaa),
    .K(32'd4)
  ) _23_ (
    .F(_12_),
    .I({ _02_, \ctr[4] , \ctr[5] , \ctr[6]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE2_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(4'h6),
    .K(32'd2)
  ) _24_ (
    .F(_13_),
    .I({ _03_, \ctr[7]  })
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y2/SLICE0_LUT" *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:7.31-7.63" *)
  LUT #(
    .INIT(2'h1),
    .K(32'd1)
  ) _25_ (
    .F(_06_),
    .I(\ctr[0] )
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE1_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _26_ (
    .CLK(_04_),
    .D(_11_),
    .Q(\ctr[5] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE0_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _27_ (
    .CLK(_04_),
    .D(_12_),
    .Q(\ctr[6] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y2/SLICE2_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _28_ (
    .CLK(_04_),
    .D(_13_),
    .Q(\ctr[7] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y2/SLICE0_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _29_ (
    .CLK(_04_),
    .D(_06_),
    .Q(\ctr[0] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y4/SLICE0_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _30_ (
    .CLK(_04_),
    .D(_07_),
    .Q(\ctr[1] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE3_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _31_ (
    .CLK(_04_),
    .D(_08_),
    .Q(\ctr[2] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE1_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _32_ (
    .CLK(_04_),
    .D(_09_),
    .Q(\ctr[3] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y4/SLICE0_DFF" *)
  (* module_not_derived = 32'd1 *)
  (* src = "./blinky.v:4.1-9.4|/home/stabo/nextpnr-pcbfpga/generic/viaduct/pcbfpga/test/cells_map.v:13.91-13.143" *)
  DFF #(
    .ENABLE_USED(1'h0),
    .RST_USED(1'h1)
  ) _33_ (
    .CLK(_04_),
    .D(_10_),
    .Q(\ctr[4] ),
    .RST_N(_05_)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X4/Y0/IO0" *)
  (* keep = 32'd1 *)
  IBUF _34_ (
    .O(_04_),
    .PAD(clk)
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X0/Y4/IO0" *)
  (* keep = 32'd1 *)
  OBUF _35_ (
    .I(\ctr[4] ),
    .PAD(leds[0])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X6/Y2/IO0" *)
  (* keep = 32'd1 *)
  OBUF _36_ (
    .I(\ctr[5] ),
    .PAD(leds[1])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X0/Y2/IO1" *)
  (* keep = 32'd1 *)
  OBUF _37_ (
    .I(\ctr[6] ),
    .PAD(leds[2])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y0/IO1" *)
  (* keep = 32'd1 *)
  OBUF _38_ (
    .I(\ctr[7] ),
    .PAD(leds[3])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X0/Y4/IO1" *)
  (* keep = 32'd1 *)
  OBUF _39_ (
    .I(\ctr[4] ),
    .PAD(leds[4])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X6/Y2/IO1" *)
  (* keep = 32'd1 *)
  OBUF _40_ (
    .I(\ctr[5] ),
    .PAD(leds[5])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X0/Y2/IO0" *)
  (* keep = 32'd1 *)
  OBUF _41_ (
    .I(\ctr[6] ),
    .PAD(leds[6])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y0/IO0" *)
  (* keep = 32'd1 *)
  OBUF _42_ (
    .I(\ctr[7] ),
    .PAD(leds[7])
  );
  (* BEL_STRENGTH = 32'd1 *)
  (* NEXTPNR_BEL = "X2/Y6/IO1" *)
  (* keep = 32'd1 *)
  IBUF _43_ (
    .O(_05_),
    .PAD(rst)
  );
  assign \leds[7]  = leds[7];
  assign \leds[6]  = leds[6];
  assign \leds[5]  = leds[5];
  assign \leds[4]  = leds[4];
  assign \leds[3]  = leds[3];
  assign \leds[2]  = leds[2];
  assign \leds[1]  = leds[1];
  assign \leds[0]  = leds[0];
endmodule
