/* Generated by Yosys 0.38+129 (git sha1 e9cd6ca9e, g++ 13.2.0-4ubuntu3 -fPIC -Os) */

(* hdlname = "opccpu" *)
(* top =  1  *)
(* src = "/home/stabo/opc/opc1/opccpu.v:1.1-64.10" *)
module opccpu(data, address, rnw, clk, reset_b);
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _000_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _001_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _002_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _003_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _004_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _005_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _006_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _007_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:54.18-54.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _008_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _009_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _010_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _011_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _012_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _013_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _014_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _015_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _016_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _017_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _018_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _019_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _020_;
  reg _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:16.23-16.69" *)
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _109_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _110_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _111_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _112_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _113_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _114_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _115_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _116_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _117_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire _118_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire _119_;
  wire _120_;
  wire _121_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:44.43-44.72|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _122_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _123_;
  wire _124_;
  wire [7:0] _125_;
  (* force_downto = 32'd1 *)
  (* src = "/home/stabo/opc/opc1/opccpu.v:0.0-0.0|/home/stabo/opc/opc1/opccpu.v:37.11-46.18|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [7:0] _126_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:8.15-8.20" *)
  reg [7:0] ACC_q;
  (* onehot = 32'd1 *)
  reg [4:0] FSM_q;
  (* src = "/home/stabo/opc/opc1/opccpu.v:10.15-10.19" *)
  reg [4:0] IR_q;
  (* src = "/home/stabo/opc/opc1/opccpu.v:11.15-11.21" *)
  reg [2:0] LINK_q;
  (* src = "/home/stabo/opc/opc1/opccpu.v:7.15-7.19" *)
  reg [10:0] OR_q;
  (* src = "/home/stabo/opc/opc1/opccpu.v:7.21-7.25" *)
  (* unused_bits = "8" *)
  wire [10:0] PC_q;
  (* src = "/home/stabo/opc/opc1/opccpu.v:1.46-1.53" *)
  output [10:0] address;
  wire [10:0] address;
  (* src = "/home/stabo/opc/opc1/opccpu.v:1.73-1.76" *)
  input clk;
  wire clk;
  (* src = "/home/stabo/opc/opc1/opccpu.v:1.27-1.31" *)
  inout [7:0] data;
  wire [7:0] data;
  (* src = "/home/stabo/opc/opc1/opccpu.v:1.84-1.91" *)
  input reset_b;
  wire reset_b;
  (* src = "/home/stabo/opc/opc1/opccpu.v:1.62-1.65" *)
  output rnw;
  wire rnw;
  (* src = "/home/stabo/opc/opc1/opccpu.v:13.15-13.26" *)
  wire writeback_w;
  assign _030_ = 8'h35 >> { _043_, _096_, _007_ };
  assign _096_ = 8'hca >> { _098_, LINK_q[0], OR_q[8] };
  assign _098_ = 16'h4000 >> { IR_q[0], _064_, IR_q[2:1] };
  assign _064_ = 4'h8 >> { IR_q[3], IR_q[4] };
  assign _007_ = 8'h87 >> { _021_, PC_q[7], _001_ };
  assign _001_ = 16'h8000 >> { PC_q[6:4], _000_ };
  assign _000_ = 16'h8000 >> PC_q[3:0];
  assign _043_ = 4'h1 >> { FSM_q[3], FSM_q[0] };
  assign _032_ = 16'hf044 >> { FSM_q[0], _058_, OR_q[8], FSM_q[2] };
  assign _033_ = 16'hf044 >> { FSM_q[0], _059_, OR_q[9], FSM_q[2] };
  assign _034_ = 16'hf044 >> { FSM_q[0], _060_, OR_q[10], FSM_q[2] };
  assign _035_ = 8'h3a >> { _028_, _120_, LINK_q[1] };
  assign _120_ = 8'h35 >> { _045_, ACC_q[1], PC_q[9] };
  assign _045_ = 16'h4000 >> { _064_, IR_q[1], IR_q[2], IR_q[0] };
  assign _028_ = 16'h4000 >> { FSM_q[1], _064_, IR_q[2], IR_q[0] };
  assign _036_ = 8'h3a >> { _028_, _121_, LINK_q[2] };
  assign _121_ = 8'h53 >> { _045_, PC_q[10], ACC_q[2] };
  assign _037_ = 16'hbbf0 >> { _027_, LINK_q[0], _066_, _109_ };
  assign _109_ = 16'hd400 >> { _044_, OR_q[7], ACC_q[7], _013_ };
  assign _013_ = 16'h1117 >> { _020_, _065_, OR_q[6], ACC_q[6] };
  assign _065_ = 16'hd400 >> { _017_, OR_q[4], ACC_q[4], _011_ };
  assign _011_ = 16'h1117 >> { _019_, _122_, OR_q[3], ACC_q[3] };
  assign _122_ = 16'hd400 >> { _015_, OR_q[1], ACC_q[1], _009_ };
  assign _009_ = 8'h17 >> { OR_q[0], ACC_q[0], LINK_q[0] };
  assign _015_ = 4'h6 >> { OR_q[2], ACC_q[2] };
  assign _019_ = 4'h8 >> { OR_q[2], ACC_q[2] };
  assign _017_ = 4'h6 >> { OR_q[5], ACC_q[5] };
  assign _020_ = 4'h8 >> { OR_q[5], ACC_q[5] };
  assign _044_ = 16'h1000 >> { IR_q[0], IR_q[1], IR_q[3:2] };
  assign _027_ = 8'hf4 >> { _028_, FSM_q[1], _041_ };
  assign _041_ = 4'h1 >> { _042_, _044_ };
  assign _042_ = 16'h0001 >> { IR_q[0], IR_q[1], IR_q[3:2] };
  assign _066_ = 16'h0fbb >> { _045_, ACC_q[0], _041_, _021_ };
  assign _039_ = 16'h0001 >> ACC_q[3:0];
  assign _040_ = 16'h0001 >> ACC_q[7:4];
  assign _026_ = 16'h4f00 >> { _061_, _067_, FSM_q[2], _038_ };
  assign _038_ = 16'h1000 >> { IR_q[0], IR_q[3], IR_q[1], IR_q[2] };
  assign _067_ = 16'h001f >> { FSM_q[4], IR_q[4], FSM_q[3:2] };
  assign _025_ = 4'hb >> { _061_, FSM_q[1] };
  assign _029_ = 16'hffe0 >> { _027_, FSM_q[1], _046_, _119_ };
  assign _119_ = 16'h0100 >> { IR_q[0], IR_q[1], IR_q[2], _064_ };
  assign _046_ = 16'h0100 >> { IR_q[1:0], IR_q[3:2] };
  assign writeback_w = 8'h40 >> { IR_q[3], _068_, IR_q[2] };
  assign _068_ = 16'h1000 >> { FSM_q[1], _061_, IR_q[0], IR_q[1] };
  assign _126_[0] = 16'hf8ff >> { _070_, _069_, _123_, PC_q[0] };
  assign _069_ = 16'hbac0 >> { LINK_q[0], _044_, _014_, _045_ };
  assign _014_ = 4'h6 >> { OR_q[0], ACC_q[0] };
  assign _123_ = 16'h0100 >> { _041_, _046_, _119_, _045_ };
  assign _070_ = 16'h0305 >> { OR_q[0], _111_, _119_, _046_ };
  assign _111_ = 8'h80 >> { OR_q[0], ACC_q[0], _042_ };
  assign _126_[1] = 16'h8fff >> { _071_, _073_, _123_, PC_q[1] };
  assign _071_ = 8'hc5 >> { OR_q[1], _072_, _046_ };
  assign _072_ = 8'h07 >> { _119_, _042_, ACC_q[1] };
  assign _073_ = 8'h07 >> { _110_, _045_, LINK_q[1] };
  assign _110_ = 16'h6900 >> { _044_, OR_q[1], ACC_q[1], _009_ };
  assign _126_[2] = 16'hf8ff >> { _074_, _112_, _123_, PC_q[2] };
  assign _074_ = 16'h3500 >> { _075_, OR_q[2], _119_, _046_ };
  assign _075_ = 16'h0777 >> { LINK_q[2], _045_, _019_, _042_ };
  assign _112_ = 16'h6900 >> { _044_, OR_q[2], ACC_q[2], _010_ };
  assign _010_ = 8'h2b >> { OR_q[1], ACC_q[1], _009_ };
  assign _126_[3] = 16'hfff8 >> { _114_, _076_, _123_, PC_q[3] };
  assign _114_ = 16'h1e00 >> { _044_, _016_, _019_, _122_ };
  assign _016_ = 4'h6 >> { OR_q[3], ACC_q[3] };
  assign _076_ = 16'heef0 >> { OR_q[3], _046_, _119_, _077_ };
  assign _077_ = 4'h8 >> { ACC_q[3], _042_ };
  assign _126_[4] = 16'hf8ff >> { _078_, _115_, _123_, PC_q[4] };
  assign _115_ = 16'h6900 >> { _044_, OR_q[4], ACC_q[4], _011_ };
  assign _078_ = 8'hc5 >> { OR_q[4], _079_, _046_ };
  assign _079_ = 8'h07 >> { _119_, _042_, ACC_q[4] };
  assign _126_[5] = 16'hf8ff >> { _080_, _116_, _123_, PC_q[5] };
  assign _116_ = 16'h6900 >> { _044_, OR_q[5], ACC_q[5], _012_ };
  assign _012_ = 8'h2b >> { OR_q[4], ACC_q[4], _011_ };
  assign _080_ = 8'hc5 >> { OR_q[5], _081_, _046_ };
  assign _081_ = 8'h07 >> { _119_, _042_, ACC_q[5] };
  assign _126_[6] = 16'hf8ff >> { _082_, _117_, _123_, PC_q[6] };
  assign _117_ = 16'h1e00 >> { _044_, _018_, _020_, _065_ };
  assign _018_ = 4'h6 >> { OR_q[6], ACC_q[6] };
  assign _082_ = 16'h0305 >> { OR_q[6], _113_, _119_, _046_ };
  assign _113_ = 8'h80 >> { OR_q[6], ACC_q[6], _042_ };
  assign _126_[7] = 16'hf8ff >> { _083_, _118_, _123_, PC_q[7] };
  assign _118_ = 16'h6900 >> { _044_, OR_q[7], ACC_q[7], _013_ };
  assign _083_ = 8'hc5 >> { OR_q[7], _084_, _046_ };
  assign _084_ = 8'h07 >> { _119_, _042_, ACC_q[7] };
  assign _047_ = 8'hca >> { _063_, PC_q[0], OR_q[0] };
  assign _063_ = 8'h01 >> { FSM_q[4], FSM_q[2], writeback_w };
  assign _049_ = 8'hca >> { _063_, PC_q[1], OR_q[1] };
  assign _050_ = 8'hca >> { _063_, PC_q[2], OR_q[2] };
  assign _051_ = 8'hca >> { _063_, PC_q[3], OR_q[3] };
  assign _052_ = 8'hca >> { _063_, PC_q[4], OR_q[4] };
  assign _053_ = 8'hca >> { _063_, PC_q[5], OR_q[5] };
  assign _054_ = 8'hca >> { _063_, PC_q[6], OR_q[6] };
  assign _055_ = 8'hca >> { _063_, PC_q[7], OR_q[7] };
  assign _056_ = 8'h3a >> { _063_, _021_, OR_q[8] };
  assign _057_ = 8'hca >> { _063_, PC_q[9], OR_q[9] };
  assign _048_ = 8'hca >> { _063_, PC_q[10], OR_q[10] };
  assign _099_ = 8'h35 >> { _043_, _087_, PC_q[0] };
  assign _087_ = 8'h35 >> { _098_, ACC_q[0], OR_q[0] };
  assign _101_ = 16'haa3c >> { _043_, PC_q[1:0], _089_ };
  assign _089_ = 8'hca >> { _098_, ACC_q[1], OR_q[1] };
  assign _102_ = 8'hca >> { _043_, _090_, _003_ };
  assign _090_ = 8'hca >> { _098_, ACC_q[2], OR_q[2] };
  assign _003_ = 8'h78 >> PC_q[2:0];
  assign _103_ = 8'hca >> { _043_, _091_, _004_ };
  assign _091_ = 8'hca >> { _098_, ACC_q[3], OR_q[3] };
  assign _004_ = 16'h7f80 >> PC_q[3:0];
  assign _104_ = 16'haa3c >> { _043_, PC_q[4], _000_, _092_ };
  assign _092_ = 8'hca >> { _098_, ACC_q[4], OR_q[4] };
  assign _105_ = 8'hca >> { _043_, _093_, _005_ };
  assign _093_ = 8'hca >> { _098_, ACC_q[5], OR_q[5] };
  assign _005_ = 8'h78 >> { PC_q[5:4], _000_ };
  assign _106_ = 8'hca >> { _043_, _094_, _006_ };
  assign _094_ = 8'hca >> { _098_, ACC_q[6], OR_q[6] };
  assign _006_ = 16'h7f80 >> { PC_q[6:4], _000_ };
  assign _107_ = 16'haa3c >> { _043_, PC_q[7], _001_, _095_ };
  assign _095_ = 8'hca >> { _098_, ACC_q[7], OR_q[7] };
  assign _108_ = 8'hca >> { _043_, _097_, _008_ };
  assign _097_ = 8'hca >> { _098_, LINK_q[1], OR_q[9] };
  assign _008_ = 16'hbf40 >> { PC_q[9], PC_q[7], _001_, _021_ };
  assign _100_ = 16'h553c >> { _043_, PC_q[10], _002_, _088_ };
  assign _002_ = 16'h4000 >> { PC_q[9], PC_q[7], _001_, _021_ };
  assign _088_ = 8'h35 >> { _098_, LINK_q[2], OR_q[10] };
  assign _024_ = 16'h4000 >> { FSM_q[2], _038_, _061_, IR_q[4] };
  assign _022_ = 8'h40 >> { FSM_q[3], _061_, IR_q[4] };
  assign _023_ = 4'h8 >> { _061_, FSM_q[0] };
  assign _062_ = 2'h1 >> writeback_w;
  assign _085_ = 16'hff80 >> { IR_q[0], _040_, _039_, IR_q[1] };
  assign _086_ = 16'h30ec >> { IR_q[1], _085_, IR_q[2], LINK_q[0] };
  assign _031_ = 16'h8fff >> { _043_, _061_, _086_, _064_ };
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[8] <= _032_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[9] <= _033_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[10] <= _034_;
  always @(posedge _124_)
    FSM_q[0] <= _025_;
  always @(posedge _124_)
    FSM_q[1] <= _026_;
  always @(posedge _124_)
    FSM_q[2] <= _022_;
  always @(posedge _124_)
    FSM_q[3] <= _023_;
  always @(posedge _124_)
    FSM_q[4] <= _024_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    LINK_q[1] <= _035_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    LINK_q[2] <= _036_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[0] <= _058_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[1] <= _059_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[2] <= _060_;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[3] <= _125_[3];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[4] <= _125_[4];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[5] <= _125_[5];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[6] <= _125_[6];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    OR_q[7] <= _125_[7];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    LINK_q[0] <= _037_;
  reg \PC_q_reg[0] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[0]  <= 1'h0;
      else \PC_q_reg[0]  <= _099_;
  assign PC_q[0] = \PC_q_reg[0] ;
  reg \PC_q_reg[1] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[1]  <= 1'h0;
      else \PC_q_reg[1]  <= _101_;
  assign PC_q[1] = \PC_q_reg[1] ;
  reg \PC_q_reg[2] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[2]  <= 1'h0;
      else \PC_q_reg[2]  <= _102_;
  assign PC_q[2] = \PC_q_reg[2] ;
  reg \PC_q_reg[3] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[3]  <= 1'h0;
      else \PC_q_reg[3]  <= _103_;
  assign PC_q[3] = \PC_q_reg[3] ;
  reg \PC_q_reg[4] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[4]  <= 1'h0;
      else \PC_q_reg[4]  <= _104_;
  assign PC_q[4] = \PC_q_reg[4] ;
  reg \PC_q_reg[5] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[5]  <= 1'h0;
      else \PC_q_reg[5]  <= _105_;
  assign PC_q[5] = \PC_q_reg[5] ;
  reg \PC_q_reg[6] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[6]  <= 1'h0;
      else \PC_q_reg[6]  <= _106_;
  assign PC_q[6] = \PC_q_reg[6] ;
  reg \PC_q_reg[7] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[7]  <= 1'h0;
      else \PC_q_reg[7]  <= _107_;
  assign PC_q[7] = \PC_q_reg[7] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) _021_ <= 1'h0;
      else _021_ <= _030_;
  reg \PC_q_reg[9] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[9]  <= 1'h0;
      else \PC_q_reg[9]  <= _108_;
  assign PC_q[9] = \PC_q_reg[9] ;
  reg \PC_q_reg[10] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:49.4-63.17" *)
  always @(posedge _124_)
    if (_031_)
      if (!_061_) \PC_q_reg[10]  <= 1'h0;
      else \PC_q_reg[10]  <= _100_;
  assign PC_q[10] = \PC_q_reg[10] ;
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[0] <= _126_[0];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[1] <= _126_[1];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[2] <= _126_[2];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[3] <= _126_[3];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[4] <= _126_[4];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[5] <= _126_[5];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[6] <= _126_[6];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (_029_) ACC_q[7] <= _126_[7];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (FSM_q[0]) IR_q[0] <= _125_[3];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (FSM_q[0]) IR_q[1] <= _125_[4];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (FSM_q[0]) IR_q[2] <= _125_[5];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (FSM_q[0]) IR_q[3] <= _125_[6];
  (* src = "/home/stabo/opc/opc1/opccpu.v:30.4-47.9" *)
  always @(posedge _124_)
    if (FSM_q[0]) IR_q[4] <= _125_[7];
  iobuft _298_ (
    .A(ACC_q[0]),
    .E(writeback_w),
    .PAD(data[0]),
    .Y(_058_)
  );
  iobuft _299_ (
    .A(ACC_q[1]),
    .E(writeback_w),
    .PAD(data[1]),
    .Y(_059_)
  );
  iobuft _300_ (
    .A(ACC_q[2]),
    .E(writeback_w),
    .PAD(data[2]),
    .Y(_060_)
  );
  iobuft _301_ (
    .A(ACC_q[3]),
    .E(writeback_w),
    .PAD(data[3]),
    .Y(_125_[3])
  );
  iobuft _302_ (
    .A(ACC_q[4]),
    .E(writeback_w),
    .PAD(data[4]),
    .Y(_125_[4])
  );
  iobuft _303_ (
    .A(ACC_q[5]),
    .E(writeback_w),
    .PAD(data[5]),
    .Y(_125_[5])
  );
  iobuft _304_ (
    .A(ACC_q[6]),
    .E(writeback_w),
    .PAD(data[6]),
    .Y(_125_[6])
  );
  iobuft _305_ (
    .A(ACC_q[7]),
    .E(writeback_w),
    .PAD(data[7]),
    .Y(_125_[7])
  );
  (* keep = 32'd1 *)
  obuf _306_ (
    .i(_047_),
    .o(address[0])
  );
  (* keep = 32'd1 *)
  obuf _307_ (
    .i(_049_),
    .o(address[1])
  );
  (* keep = 32'd1 *)
  obuf _308_ (
    .i(_048_),
    .o(address[10])
  );
  (* keep = 32'd1 *)
  obuf _309_ (
    .i(_050_),
    .o(address[2])
  );
  (* keep = 32'd1 *)
  obuf _310_ (
    .i(_051_),
    .o(address[3])
  );
  (* keep = 32'd1 *)
  obuf _311_ (
    .i(_052_),
    .o(address[4])
  );
  (* keep = 32'd1 *)
  obuf _312_ (
    .i(_053_),
    .o(address[5])
  );
  (* keep = 32'd1 *)
  obuf _313_ (
    .i(_054_),
    .o(address[6])
  );
  (* keep = 32'd1 *)
  obuf _314_ (
    .i(_055_),
    .o(address[7])
  );
  (* keep = 32'd1 *)
  obuf _315_ (
    .i(_056_),
    .o(address[8])
  );
  (* keep = 32'd1 *)
  obuf _316_ (
    .i(_057_),
    .o(address[9])
  );
  (* keep = 32'd1 *)
  ibuf _317_ (
    .i(clk),
    .o(_124_)
  );
  (* keep = 32'd1 *)
  ibuf _318_ (
    .i(reset_b),
    .o(_061_)
  );
  (* keep = 32'd1 *)
  obuf _319_ (
    .i(_062_),
    .o(rnw)
  );
  assign _125_[2:0] = { _060_, _059_, _058_ };
endmodule
